#!/usr/bin/env bash
#
# function to browse borg backups in finder

# reads input argument
device_backup="$1"

# if no argument is passed, read device name as hostname
if [ -z $device_backup ]; then
    device_backup=$HOSTNAME
    echo "No specific device backup specified. Mounting $device_backup backup."
fi

# check that its a computer with GUI
if [ "$(device)" = "laptop" ]; then

    repo=$BACKUP_DIR/$device_backup

    # create tmp mountpoint
    mountpoint=/tmp/browse_backup
    mkdir -p $mountpoint

    # mount backup
    echo "mounting $BACKUP_SERVER:$repo to $mountpoint."
    sudo borg mount -o allow_other $BACKUP_SERVER:$repo $mountpoint

    if [ "$(uname)" = "Darwin" ]; then
        # open mounted backup in finder
        echo "opening in finder."
        open $mountpoint
    fi

    # Wait for user confirmation to unmount
    while true; do
        read -p "Enter 'y' to unmount the backup folder: " response
        if [[ "$response" == "y" ]]; then
            sudo borg umount $mountpoint
            echo "Backup unmounted."
            break
        else
            echo "Waiting for 'y' to unmount..."
        fi
    done

    # Clean up the temporary directory
    rm -r $mountpoint

else
    echo "[ERROR] This computer does not have a GUI to browse backups!"
    exit 1
fi
