#!/bin/bash

# get the app name
app="$1"

# Check if app argument is provided
if [ -z "$app" ]; then
    echo "[ERROR] No application specified. Usage: $0 <app-name>"
    exit 1
fi

# Define the install script path
install_script="$DOTFILES/$app/install.sh"

# Check if the install script exists
if [ ! -f "$install_script" ]; then
    echo "[ERROR] Install script for $app not found at $install_script."
    exit 1
fi

# Run the install script and check for errors
echo "Installing $app config..."
/bin/bash "$install_script"

if [ $? -eq 0 ]; then
    echo "[SUCCESS] $app config installed successfully."
else
    echo "[ERROR] Failed to install $app config. Please check the install script for errors."
    exit 1
fi
