#!/bin/bash

echo -n "Enter the note name: "
read note_name

formatted_name=$(echo "$note_name" | tr ' ' '-')

notes_folder="$CLOUD/Second-Brain/inbox"

note_path="${notes_folder}/${formatted_name}.md"

echo "# $note_name" > "$note_path"

nvim "$note_path"
