#!/bin/bash

# Sync Nexcloud Second-Brain Obsidian vault with iCloud vault
# Make sure unison is installed!

unison -batch -auto -prefer newer $CLOUD/Second-Brain /Users/henrikzujeddeloh/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Second-Brain
