#!/usr/bin/env bash
#
# open tmp.md

tmp_file="$CLOUD/Second-Brain/tmp.md"

# check that tmp.md exists
if [ ! -f "$tmp_file" ]; then
    echo "[ERROR] $tmp_file does not exist."
    exit 1
fi

nvim "$tmp_file"
