#!/bin/bash

# reads input argument
device="$1"

# runs corresponding update script
if [ -z $device ]; then
    # if no argument is passed, read device name as hostname
    device=$(hostname)
fi

if [ $device = "proton" ] || [ $device = "raspberrypi" ]; then
    echo "Running proton update" 
    /bin/bash $SCRIPTS/proton/update.sh

elif [ $device = "electron" ]; then
    echo "Running electron update"
    /bin/bash $SCRIPTS/electron/update.sh

elif [ $device = "photon" ]; then
    echo "Running photon update"
    /bin/bash $SCRIPTS/photon/update.sh

elif [ $device = "neutron" ]; then
    echo "Running neutron update"
    /bin/bash $SCRIPTS/neutron/update.sh

else
    echo $device" does not have an update script"

fi
